[package]
name = "xtask-common"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = [
    "derive",
    "cargo",
    "env",
    "unicode",
    "wrap_help",
] }
xshell = "0.2.7"
